### ISSUE TITLE
test_emis_summary failling

### ISSUE THREAD

**Issue by rafapereirabr** [rafapereirabr/gtfs2emis#68]
> Backtrace:
>     x
>  1. \-... %>% ... at test_emis_grid.R:6:2
> -- Failure (test_emis_summary.R:47:3): emis_summary ----------------------------
> nrow(summary_time) not equal to 10.
> 1/1 mismatches
> [1] 4 - 10 == -6
> -- Failure (test_emis_summary.R:50:3): emis_summary ----------------------------
> as.numeric(sum(summary_time$emi)) not equal to 63985.96.
> 1/1 mismatches
> [1] 30883 - 63986 == -33103
> -- Failure (test_emis_summary.R:51:3): emis_summary ----------------------------
> as.numeric(sum(summary_veh$emi)) not equal to 63985.96.
> 1/1 mismatches
> [1] 30883 - 63986 == -33103
> -- Failure (test_emis_summary.R:52:3): emis_summary ----------------------------
> as.numeric(sum(summary_pol$emi)) not equal to 63985.96.
> 1/1 mismatches
> [1] 30883 - 63986 == -33103

**Comment by Joaobazzo** [comment]
[38c5e4a](https://github.com/rafapereirabr/gtfs2emis/commit/38c5e4a1b505a357bbc757ccbd2632972747ad0f)  should fix it
